---
- name: opensuse | installing dependencies
  zypper:
    name: "{{ item }}"
    state: "present"
  become: true
  with_items:
    - 'python-devel'
    - 'python-pip'

- name: opensuse | installing redis
  zypper:
    name: "redis"
    state: "present"
  become: true
  notify:
    - 'start redis'
  when: not redis_install_from_source
