---
vm_template: ubuntu1604-packer-template

vms:
  - name: consul-1
    # customization:
    #   dns_servers: "{{ dns_nameservers }}"
    #   domain: "{{ pri_domain_name }}"
    groups:
      - ansible_provisioned
      - consul_cluster
    networks:
      - name: VSS-VLAN-102
        type: dhcp
        device_type: vmxnet3
        # ip:
        # netmask:
        # gateway:
    state: present
    vm_hardware:
      memory_mb: 1024
      num_cpus: 1
  - name: consul-2
    # customization:
    #   dns_servers: "{{ dns_nameservers }}"
    #   domain: "{{ pri_domain_name }}"
    groups:
      - ansible_provisioned
      - consul_cluster
    networks:
      - name: VSS-VLAN-102
        type: dhcp
        device_type: vmxnet3
        # ip:
        # netmask:
        # gateway:
    state: present
    vm_hardware:
      memory_mb: 1024
      num_cpus: 1
  - name: consul-3
    # customization:
    #   dns_servers: "{{ dns_nameservers }}"
    #   domain: "{{ pri_domain_name }}"
    groups:
      - ansible_provisioned
      - consul_cluster
    networks:
      - name: VSS-VLAN-102
        type: dhcp
        device_type: vmxnet3
        # ip:
        # netmask:
        # gateway:
    state: present
    vm_hardware:
      memory_mb: 1024
      num_cpus: 1
