---
- name: debian | adding haproxy ppa
  apt_repository:
    repo: "{{ haproxy_debian_repo }}"
    state: "present"
    update_cache: yes
  become: true
  when: ansible_distribution == "Ubuntu"

- name: debian | installing haproxy and socat
  apt:
    name: "{{ item }}"
    state: "present"
  become: true
  with_items:
    - 'haproxy'
    - 'hatop'
    - 'socat'

- name: debian | ensuring haproxy is enabled
  service:
    name: "haproxy"
    enabled: yes
  become: true
  when: not ansible_check_mode
